- name: Install Docker and required packages
  hosts: all
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
      tags: [packages]

    - name: Install aptitude
      apt:
        name: aptitude
        state: present
      tags: [packages]

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: present
        update_cache: no
      tags: [packages]

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        validate_certs: yes
      tags: [docker]

    - name: Add Docker Repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      tags: [docker]

    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes
      tags: [docker]

    - name: Install docker-ce
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: no
      tags: [docker]

    - name: Install Docker Module for Python
      apt:
        name: python3-docker
        state: present
      tags: [python]

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present 
      tags: [docker]
